/*
TESTES

Antes de um software ou funcionalidade subrir para a pordução é necessario 
executar a etapa de testes onde são detectados possiveis problemas na aplicação 
,evitando que esses cheguem ao cliente final.

Testes manuais como o mome já diz e quando o desenvolvedor faz o teste da funcionalidade,
manualmente, em sistemas menores esse tipo de teste é normal o problema é quando estamos 
lidando com sistemas interprise capazes de fazer a união entre até 15 tabelas para montar
um registro, nesse caso o TDD precisa ser usado.

Teste automatizados são funções ou softwares escritos pelos desenvolvedores para testar 
aplicações.Em softwares de grande porte é arriscado demais executar testes manuais porque 
o desenvolvedor por esquecer de testar um campo ou um funcionalidade espepecifica que pode 
acarretar problemas criticos na integridade da base de dados.

Testes unitarios 
E um tipo de teste que serve para testar uma função especifica e somente ela  

Teste integration 
É um tipo de teste que testa uma função composta por outras funções, eo mais usado
atualmente. 

CDD CODE DRIVEN DEVELOPMENT (primeiro codigo depois teste, desenvolvimento normal)

Vantagens do uso de TDD













*/